"""Body — runtime introspection of the infrastructure spec (BODY.md).

BODY.md is the self-knowledge document — it lists every actor, every
self-awareness component, every scraper, every expertise, every concept,
the test inventory, the dep stack, and the env-var registry. Most of it
is autogenerated (`tools/regenerate_body.py`) from the live codebase.

The hand-written sections are *invariants* — claims about the system
that must hold true regardless of code changes. They live between
``<!-- INVARIANTS:start -->`` and ``<!-- INVARIANTS:end -->`` markers.

Used by Actor 8 (future) to verify the live system matches the spec.
"""
from __future__ import annotations

import re
from pathlib import Path

INVARIANTS_PATTERN = re.compile(
    r"<!--\s*INVARIANTS:start\s*-->(.*?)<!--\s*INVARIANTS:end\s*-->",
    re.DOTALL,
)


def read_invariants(repo_root: Path) -> str:
    """Read the hand-written invariants section from BODY.md.

    Returns an empty string when the markers are absent — BODY.md may be
    a freshly-scaffolded file in which case the invariant block hasn't
    been written yet.
    """
    body = repo_root / "BODY.md"
    if not body.exists():
        return ""
    text = body.read_text(encoding="utf-8")
    m = INVARIANTS_PATTERN.search(text)
    return m.group(1).strip() if m else ""
