#!/usr/bin/env python3
"""Fail if any forbidden source name appears in the repo.

This repo is a public, didactic reference. Real source names (banks,
expert analysts, podcasts, wire services, hostnames, bot handles) are
replaced with anonymized aliases throughout. See `docs/source_naming.md`.

This check scans every text file in the repo, normalizes every word, and
hashes it. If any hash matches an entry in `.anonymization-blocklist.sha256`,
the build fails with the file + line number.

The plaintext blocklist `.anonymization-blocklist.txt` is gitignored. Only
the hashed version ships, so readers can't reverse the list from the repo.

Usage:
  python tools/check_anonymization.py              # check repo
  python tools/check_anonymization.py --build      # rebuild blocklist
                                                   # from plaintext + commit

Invoked by:
  - pre-commit hook
  - CI workflow (.github/workflows/anonymization_check.yml)
  - tests/test_anonymization.py
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLAINTEXT = REPO / ".anonymization-blocklist.txt"
HASHED = REPO / ".anonymization-blocklist.sha256"

# Directories to skip
SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "node_modules",
    "build",
    "dist",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}

# File extensions to scan (text only)
SCAN_EXTS = {".md", ".py", ".yaml", ".yml", ".json", ".toml", ".txt", ".mdc", ".mmd"}

# These two files are themselves part of the enforcement machinery and
# may legitimately reference the *concept* of forbidden tokens. The
# plaintext blocklist is gitignored, but list both here as belt-and-suspenders.
SKIP_FILES = {
    PLAINTEXT.name,
    HASHED.name,
    "check_anonymization.py",
}


def _hash_token(token: str) -> str:
    """Hash a single normalized token. SHA256, lowercase, hex digest."""
    return hashlib.sha256(token.lower().strip().encode("utf-8")).hexdigest()


def load_hashed_blocklist() -> set[str]:
    if not HASHED.exists():
        return set()
    out: set[str] = set()
    for line in HASHED.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.add(line)
    return out


def build_blocklist_from_plaintext() -> int:
    """Rebuild the hashed blocklist from the local plaintext file."""
    if not PLAINTEXT.exists():
        print(f"ERROR: {PLAINTEXT} not found.", file=sys.stderr)
        print(
            "Create it with one forbidden token per line, then re-run with --build.",
            file=sys.stderr,
        )
        return 2
    tokens: list[str] = []
    for line in PLAINTEXT.read_text(encoding="utf-8").splitlines():
        t = line.strip()
        if not t or t.startswith("#"):
            continue
        tokens.append(t)
    hashes = sorted({_hash_token(t) for t in tokens})
    HASHED.write_text(
        "# SHA256 hashes of forbidden source names.\n"
        "# Generated by tools/check_anonymization.py --build.\n"
        "# Plaintext source: .anonymization-blocklist.txt (gitignored).\n"
        "# DO NOT COMMIT THE PLAINTEXT.\n"
        + "\n".join(hashes)
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(hashes)} hashed tokens to {HASHED.name}.")
    return 0


# Token pattern: word characters, possibly with internal hyphens or dots
TOKEN_PAT = re.compile(r"[A-Za-z][A-Za-z0-9._-]{2,}")


def scan_repo(blocklist: set[str]) -> list[tuple[Path, int, str]]:
    """Return list of (file, line_number, offending_token) for any leak."""
    leaks: list[tuple[Path, int, str]] = []
    if not blocklist:
        return leaks

    for p in REPO.rglob("*"):
        if not p.is_file():
            continue
        if any(seg in p.parts for seg in SKIP_DIRS):
            continue
        if p.name in SKIP_FILES:
            continue
        if p.suffix.lower() not in SCAN_EXTS:
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for line_no, line in enumerate(text.splitlines(), start=1):
            for token in TOKEN_PAT.findall(line):
                if _hash_token(token) in blocklist:
                    leaks.append((p, line_no, token))
    return leaks


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--build",
        action="store_true",
        help="Rebuild .anonymization-blocklist.sha256 from .anonymization-blocklist.txt (gitignored)",
    )
    args = parser.parse_args()

    if args.build:
        return build_blocklist_from_plaintext()

    blocklist = load_hashed_blocklist()
    if not blocklist:
        print(
            "WARNING: .anonymization-blocklist.sha256 is empty or missing — no enforcement active.\n"
            "         To populate: create .anonymization-blocklist.txt (gitignored),\n"
            "         then run `python tools/check_anonymization.py --build`.",
            file=sys.stderr,
        )
        # Don't fail the build when the blocklist is empty — that would
        # block the first commit before anyone has had a chance to set it up.
        return 0

    leaks = scan_repo(blocklist)
    if leaks:
        print("Anonymization check failed — real source names detected:", file=sys.stderr)
        for path, line_no, token in leaks:
            rel = path.relative_to(REPO)
            # Don't print the token itself in the failure message — that would
            # leak it to CI logs (which may be public). Print a fingerprint.
            fp = _hash_token(token)[:10]
            print(f"  {rel}:{line_no}  (token fp: {fp}…)", file=sys.stderr)
        print("", file=sys.stderr)
        print(
            "Replace with the appropriate alias from docs/source_naming.md\n"
            "(Bank1, Expert1, Podcast1, etc.) and re-run.",
            file=sys.stderr,
        )
        return 1

    print(f"Anonymization check passed ({len(blocklist)} forbidden tokens, none found).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
